// File generated by: https://github.com/mrange/WebSourceInclude
package scala_app
package web_source_include.streams

trait PushStream[+T] {
  def build(r: T => Boolean): Boolean
}

object PushStream {
  def empty = new PushStream[Nothing] {
    def build(r: Nothing => Boolean): Boolean = true
  }
}

trait Log {
  def log(m: String): Unit
}
